package utiles;

public @interface Querys {
	
	public static String TraerOrdenesDisponibles = "SELECT * FROM (SELECT DISTINCT row_number() over(partition by b.chk_num order by date_closed asc) as  Posision,a.id as id, b.chk_num, date_open, date_closed, isnull(name,' ') as name, date_send,date_delete, [zone],a.chk_seq FROM micros.order_dtl a inner join micros.chk_dtl b on a.chk_seq = b.chk_seq where date_send is null and date_closed > DATEADD(mi,-30,GETDATE()) and zone<100 and b.order_type_seq != 3 order by date_closed asc) x where x.posision = 1";
	//QUERY DE ABAJO ES PARA LOS QUE TENGAN AUTOKING
	//public static String TraerOrdenesDisponibles = "SELECT a.id, a.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl a left join micros.chk_dtl b  on a.chk_num = b.chk_num  where date_send is null and date_closed >  DATEADD(mi,-30,GETDATE()) and zone<100 and b.order_type_seq != 3  order by date_closed asc";
	public static String TraerOrdenesDisponiblesZ1 = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is null and a.date_closed >  DATEADD(mi,-30,GETDATE()) and zone=1 order by a.date_closed asc";
	public static String TraerOrdenesDisponiblesZ2 = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send, a.date_delete, [zone], a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is null and a.date_closed >  DATEADD(mi,-30,GETDATE()) and zone=2 order by a.date_closed asc";
	public static String TraerOrdenesDisponiblesZ3 = "SELECT id, chk_num, date_open, date_closed, name, date_send,date_delete, [zone],chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where date_send is null and date_closed >  DATEADD(mi,-30,GETDATE()) and zone=3 order by date_closed asc";
	public static String TraerOrdenesDisponiblesZ4 = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send, a.date_delete, [zone], a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is null and a.date_closed >  DATEADD(mi,-30,GETDATE()) and zone=4 order by a.date_closed asc";
	//public static String TraerOrdenesDisponibleslifo = "SELECT id, chk_num, date_open, date_closed, name, date_send,date_delete, [zone],chk_seq FROM micros.order_dtl where date_send is null and date_closed >  DATEADD(mi,-30,GETDATE())  and zone<100 order by date_closed desc";
	public static String TraerOrdenesDisponibleslifo = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send, a.date_delete, [zone], a.chk_seq FROM micros.order_dtl a left join micros.chk_dtl b  on a.chk_seq = b.chk_seq  where date_send is null and a.date_closed >  DATEADD(mi,-30,GETDATE())   and zone<100 and b.order_type_seq != 3 order by a.date_closed desc";
	public static String TraerOrdenesDisponiblesZ1lifo = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is null and a.date_closed >  DATEADD(mi,-30,GETDATE()) and zone=1 order by a.date_closed desc";
	public static String TraerOrdenesDisponiblesZ2lifo = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is null and a.date_closed >  DATEADD(mi,-30,GETDATE()) and zone=2 order by a.date_closed desc";
	public static String TraerOrdenesDisponiblesZ3lifo = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is null and a.date_closed >  DATEADD(mi,-30,GETDATE()) and zone=3 order by a.date_closed desc";
	public static String TraerOrdenesDisponiblesZ4lifo = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is null and a.date_closed >  DATEADD(mi,-30,GETDATE()) and zone=4 order by a.date_closed desc";
	//public static String TraerOrdenesDisponiblesZ1yZ2lifo = "SELECT id, chk_num, date_open, date_closed, name, date_send,date_delete, [zone],chk_seq FROM micros.order_dtl where date_send is null and date_closed >  DATEADD(mi,-30,GETDATE()) and (zone=1 or zone=2) order by date_closed desc";
	public static String TraerOrdenesDisponiblesZ1yZ2lifo = "SELECT * FROM (SELECT DISTINCT row_number() over(partition by b.chk_num order by date_closed asc) as  Posision,a.id as id, b.chk_num, date_open, date_closed, isnull(name,' ') as name, date_send,date_delete, [zone],a.chk_seq FROM  micros.order_dtl a inner join micros.chk_dtl b on a.chk_seq = b.chk_seq where date_send is null and date_closed > DATEADD(mi,-30,GETDATE())  and zone<100 and b.order_type_seq != 3 order by date_closed asc) x where x.posision = 1";
	
	public static String TraerOrdenesDisponiblesZ3yZ4lifo = "SELECT id, chk_num, date_open, date_closed, name, date_send,date_delete, [zone],chk_seq FROM micros.order_dtl where date_send is null and date_closed >  DATEADD(mi,-30,GETDATE()) and (zone=3 or zone=4) order by date_closed desc";
	
	public static String PantallaTraerOrdenesEnviadas = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send, a.date_delete, [zone], a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq WHERE a.date_send IS NOT NULL AND a.date_delete IS NULL AND a.date_send > DATEADD(mi,-30,GETDATE()) ORDER BY a.date_send DESC";
	public static String PantallaTraerOrdenesEnviadasZ1 = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is not null AND a.date_delete IS NULL AND  a.date_send >  DATEADD(mi,-30,GETDATE()) and zone=1 order by a.date_send desc";
	public static String PantallaTraerOrdenesEnviadasZ2 = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is not null AND a.date_delete IS NULL AND  a.date_send >  DATEADD(mi,-30,GETDATE()) and zone=2 order by a.date_send desc";
	public static String PantallaTraerOrdenesEnviadasZ3 = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is not null AND a.date_delete IS NULL AND  a.date_send >  DATEADD(mi,-30,GETDATE()) and zone=3 order by a.date_send desc";
	public static String PantallaTraerOrdenesEnviadasZ4 = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is not null AND a.date_delete IS NULL AND  a.date_send >  DATEADD(mi,-30,GETDATE()) and zone=4 order by a.date_send desc";
	public static String PantallaTraerOrdenesEnviadasZ1yZ2 = "SELECT * FROM (SELECT distinct row_number() over(partition by b.chk_num order by date_closed asc) as  Posision,a.id as id, b.chk_num, date_open, date_closed, isnull(name, ' ') as name, date_send, date_delete, [zone], a.chk_seq FROM micros.order_dtl a left join micros.chk_dtl b on a.chk_seq = b.chk_seq WHERE date_send IS NOT NULL  and date_delete is null AND date_send > DATEADD(mi,-30,GETDATE()) and b.order_type_seq != 3 ORDER BY date_send DESC) x where x.posision = 1";
	public static String PantallaTraerOrdenesEnviadasZ3yZ4 = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is not null AND a.date_delete IS NULL AND  a.date_send >  DATEADD(mi,-30,GETDATE()) and (zone=3 or zone=4) order by a.date_send desc";
	
	public static String TraerOrdenesEnviadas = "SELECT * FROM (SELECT distinct row_number() over(partition by b.chk_num order by date_closed asc) as  Posision,a.id as id, b.chk_num, a.date_open, a.date_closed, isnull(name, ' ') as name, a.date_send, a.date_delete, [zone], a.chk_seq FROM micros.order_dtl a left join micros.chk_dtl b on a.chk_seq = b.chk_seq WHERE a.date_send IS NOT NULL  AND a.date_delete IS NULL  AND a.date_send > DATEADD(mi,-30,GETDATE()) and b.order_type_seq != 3 ORDER BY a.date_send DESC) x where x.posision = 1";
	public static String TraerOrdenesEnviadasZ1 = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is not null  AND  a.date_send >  DATEADD(mi,-30,GETDATE()) and zone=1 order by a.date_send desc";
	public static String TraerOrdenesEnviadasZ2 = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is not null  AND  a.date_send >  DATEADD(mi,-30,GETDATE()) and zone=2 order by a.date_send desc";
	public static String TraerOrdenesEnviadasZ3 = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is not null  AND  a.date_send >  DATEADD(mi,-30,GETDATE()) and zone=3 order by a.date_send desc";
	public static String TraerOrdenesEnviadasZ4 = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is not null  AND  a.date_send >  DATEADD(mi,-30,GETDATE()) and zone=4 order by a.date_send desc";
	
	
	
	
	
	public static String Ultimas6EnviadasyOrdenadas = "(SELECT top 6 zone, b.chk_num , 1 FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq WHERE a.date_send IS NOT NULL AND a.date_send > DATEADD(mi,-30,GETDATE()) ORDER BY a.date_send DESC) UNION ALL (SELECT top 6 zone, b.chk_num ,0 FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is null and a.date_closed >  DATEADD(mi,-30,GETDATE())  and zone<100 order by a.date_closed asc)";
	
	
	
	public static String TraerOrdenesEnviadasClientez1 = "SELECT top 6 a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send, a.date_delete, zone, a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq  WHERE a.date_send IS NOT NULL AND a.date_send > DATEADD(mi,-30,GETDATE()) AND zone=1 ORDER BY a.date_send DESC";
	public static String TraerOrdenesEnviadasClientez2 = "SELECT top 6 a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send, a.date_delete, zone, a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq  WHERE a.date_send IS NOT NULL AND a.date_send > DATEADD(mi,-30,GETDATE()) AND zone=2 ORDER BY a.date_send DESC";
	public static String TraerOrdenesEnviadasClientez3 = "SELECT top 6 a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send, a.date_delete, zone, a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq  WHERE a.date_send IS NOT NULL AND a.date_send > DATEADD(mi,-30,GETDATE()) AND zone=3 ORDER BY a.date_send DESC";
	public static String TraerOrdenesEnviadasClientez4 = "SELECT top 6 a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send, a.date_delete, zone, a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq  WHERE a.date_send IS NOT NULL AND a.date_send > DATEADD(mi,-30,GETDATE()) AND zone=4 ORDER BY a.date_send DESC";
	//public static String InsertarOrdenes = "INSERT INTO micros.order_dtl SELECT c.chk_num, c.chk_open_date_time AS date_open, c.chk_clsd_date_time AS date_closed, NULL AS date_send, substring(CAST(c.id AS VARCHAR),1,16) AS name, 1, NULL AS id FROM micros.chk_dtl AS c LEFT JOIN micros.order_dtl AS o ON o.chk_num = c.chk_num WHERE chk_open = 'F' AND o.chk_num IS NULL AND chk_clsd_date_time > DATEADD(mi,-30,GETDATE()) ORDER BY chk_clsd_date_time DESC";
	//public static String InsertarOrdenes = "INSERT INTO micros.order_dtl SELECT c.chk_num, c.chk_open_date_time AS date_open, c.chk_clsd_date_time AS date_closed, NULL AS date_send, substring(CAST(c.id AS VARCHAR),1,16) AS name, CASE WHEN ISNULL(uz.zone,1)=1 THEN 1 ELSE uz.zone END AS zona, NULL AS id FROM micros.chk_dtl AS c LEFT JOIN micros.order_dtl AS o ON o.chk_num = c.chk_num LEFT JOIN micros.trans_dtl td ON td.chk_seq=c.chk_seq LEFT JOIN micros.uws_zone uz ON uz.uws_seq=td.uws_seq WHERE chk_open = 'F' AND o.chk_num IS NULL AND chk_clsd_date_time > DATEADD(mi,-30,GETDATE()) ORDER BY chk_clsd_date_time DESC";
	public static String InsertarOrdenes = "INSERT INTO micros.order_dtl \r\n"
			+ "SELECT DISTINCT CASE WHEN (c.rvc_seq = 6  and isnumeric(LEFT(trim(c.id), charindex(' ',c.id) -1))=1 and c.id is not null) \r\n"
			+ "then CAST(LEFT(trim(c.id), charindex(' ',c.id) -1) AS INT)  ELSE CAST(c.chk_num AS INT) END AS chk_num, c.chk_open_date_time AS date_open, c.chk_clsd_date_time AS date_closed, \r\n"
			+ "NULL AS date_send,NULL as date_delete, case when (c.rvc_seq = 6  and isnumeric(LEFT(trim(c.id), charindex(' ',c.id) -1))=1 \r\n"
			+ "and c.id is not null) then substring(c.id, charindex(' ',trim(c.id)) +1,15) ELSE substring(CAST(c.id AS VARCHAR),1,16) END AS name, \r\n"
			+ "CASE WHEN ISNULL(uz.zone,1)=1 THEN 1 ELSE uz.zone END AS zona, NULL AS id, c.chk_seq \r\n"
			+ "FROM micros.chk_dtl AS c \r\n"
			+ "LEFT JOIN micros.order_dtl AS o ON o.chk_seq = c.chk_seq \r\n"
			+ "LEFT JOIN micros.trans_dtl td ON td.chk_seq=c.chk_seq \r\n"
			+ "LEFT JOIN micros.uws_zone uz ON uz.uws_seq=td.uws_seq WHERE chk_open = 'F'   \r\n"
			+ "AND o.chk_seq IS NULL AND chk_clsd_date_time > DATEADD(mi,-30,GETDATE()) \r\n"
			+ "ORDER BY chk_clsd_date_time DESC";
	//public static String TraerCajas = "SELECT d.uws_seq, d.obj_num, CASE WHEN ISNULL(z.zone,0)=0 THEN 1 ELSE z.zone END AS zone FROM micros.uws_def d LEFT JOIN micros.uws_zone z ON z.uws_seq=d.uws_seq";
	public static String TraerCajas = "SELECT d.uws_seq, dd.name, d.obj_num, CASE WHEN ISNULL(z.zone,0)=0 THEN 1 ELSE z.zone END AS zone FROM micros.uws_def d LEFT JOIN micros.uws_zone z ON z.uws_seq=d.uws_seq LEFT JOIN micros.dev_def dd ON dd.obj_num=d.obj_num WHERE  dd.name like '%UWS%' ORDER by dd.name";
	public static String TraerConfig ="select oc.id,oc.fecha,oc.alertA,oc.AlertB,oc.AlertC from micros.micros.order_config oc where oc.id=1";
	public static String TraerLCD = "select lcd_id,zone from micros.lcd_zone";
	public static String TraerConfigLCD = "SELECT DISTINCT lz.lcd_id AS lcd_id, isnull(l1.zone,0) AS z1, isnull(l2.zone,0) AS z2, isnull(l3.zone,0) AS z3, isnull(l4.zone,0) AS z4, isnull(l100.zone,0) AS sz FROM micros.lcd_zone lz LEFT JOIN micros.lcd_zone l1 ON lz.lcd_id=l1.lcd_id AND l1.zone=1 LEFT JOIN micros.lcd_zone l2 ON lz.lcd_id=l2.lcd_id AND l2.zone=2 LEFT JOIN micros.lcd_zone l3 ON lz.lcd_id=l3.lcd_id AND l3.zone=3 LEFT JOIN micros.lcd_zone l4 ON lz.lcd_id=l4.lcd_id AND l4.zone=4 LEFT JOIN micros.lcd_zone l100 ON lz.lcd_id=l100.lcd_id AND l100.zone=100";
	public static String TraerConfigLCDxId ="SELECT DISTINCT lz.lcd_id AS lcd_id, isnull(l1.zone,0) AS z1, isnull(l2.zone,0) AS z2, isnull(l3.zone,0) AS z3, isnull(l4.zone,0) AS z4, isnull(l100.zone,0) AS sz FROM micros.lcd_zone lz LEFT JOIN micros.lcd_zone l1 ON lz.lcd_id=l1.lcd_id AND l1.zone=1 LEFT JOIN micros.lcd_zone l2 ON lz.lcd_id=l2.lcd_id AND l2.zone=2 LEFT JOIN micros.lcd_zone l3 ON lz.lcd_id=l3.lcd_id AND l3.zone=3 LEFT JOIN micros.lcd_zone l4 ON lz.lcd_id=l4.lcd_id AND l4.zone=4 LEFT JOIN micros.lcd_zone l100 ON lz.lcd_id=l100.lcd_id AND l100.zone=100 WHERE lz.lcd_id=?";

	public static String TraerOrdenesEnviadaslcd = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send, a.date_delete, [zone], a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_se WHERE a.date_send IS NOT NULL AND a.date_delete IS NULL AND a.date_send > DATEADD(mi,-30,GETDATE()) $$$ ORDER BY a.date_send DESC";
	public static String TraerOrdenesDisponibleslifoLCD = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send,a.date_delete, [zone],a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is null and a.date_closed >  DATEADD(mi,-30,GETDATE())  and zone<100 $$$ order by a.date_closed desc";

	public static String TraerTablet = "select lcd_id,zone from micros.lcd_zone";
	public static String TraerConfigTablet = "SELECT DISTINCT lz.tablet_id AS tablet_id, ISNULL(l1.zone,0) AS z1, ISNULL(l2.zone,0) AS z2, ISNULL(l3.zone,0) AS z3, ISNULL(l4.zone,0) AS z4, ISNULL(l100.zone,0) AS sz FROM micros.tablet_zone lz LEFT JOIN micros.tablet_zone l1 ON lz.tablet_id=l1.tablet_id AND l1.zone=1 LEFT JOIN micros.tablet_zone l2 ON lz.tablet_id=l2.tablet_id AND l2.zone=2 LEFT JOIN micros.tablet_zone l3 ON lz.tablet_id=l3.tablet_id AND l3.zone=3 LEFT JOIN micros.tablet_zone l4 ON lz.tablet_id=l4.tablet_id AND l4.zone=4 LEFT JOIN micros.tablet_zone l100 ON lz.tablet_id=l100.tablet_id AND l100.zone=100 order by lz.tablet_id";
	public static String TraerConfigTabletxId ="SELECT DISTINCT lz.tablet_id AS tablet_id, ISNULL(l1.zone,0) AS z1, ISNULL(l2.zone,0) AS z2, ISNULL(l3.zone,0) AS z3, ISNULL(l4.zone,0) AS z4, ISNULL(l100.zone,0) AS sz FROM micros.tablet_zone lz LEFT JOIN micros.tablet_zone l1 ON lz.tablet_id=l1.tablet_id AND l1.zone=1 LEFT JOIN micros.tablet_zone l2 ON lz.tablet_id=l2.tablet_id AND l2.zone=2 LEFT JOIN micros.tablet_zone l3 ON lz.tablet_id=l3.tablet_id AND l3.zone=3 LEFT JOIN micros.tablet_zone l4 ON lz.tablet_id=l4.tablet_id AND l4.zone=4 LEFT JOIN micros.tablet_zone l100 ON lz.tablet_id=l100.tablet_id AND l100.zone=100 WHERE lz.tablet_id=?";
	
	public static String TraerOrdenesDisponiblesTablet = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send, a.date_delete, [zone], a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq where a.date_send is null and a.date_closed >  DATEADD(mi,-30,GETDATE())  and zone<100 $$$ order by a.date_closed asc";
	public static String TraerOrdenesEnviadasTablet = "SELECT a.id, b.chk_num, a.date_open, a.date_closed, a.name, a.date_send, a.date_delete, [zone], a.chk_seq FROM micros.order_dtl A inner join micros.chk_dtl B on A.chk_seq = b.chk_seq WHERE a.date_send IS NOT NULL  AND a.date_send > DATEADD(mi,-30,GETDATE()) $$$ ORDER BY a.date_send DESC";
}
